// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: magnetar.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryNodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *QueryNodesReq) Reset() {
	*x = QueryNodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesReq) ProtoMessage() {}

func (x *QueryNodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesReq.ProtoReflect.Descriptor instead.
func (*QueryNodesReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{0}
}

func (x *QueryNodesReq) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

type QueryNodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodePretty `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *QueryNodesResp) Reset() {
	*x = QueryNodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesResp) ProtoMessage() {}

func (x *QueryNodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesResp.ProtoReflect.Descriptor instead.
func (*QueryNodesResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{1}
}

func (x *QueryNodesResp) GetNodes() []*NodePretty {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodePretty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels []*LabelPretty `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *NodePretty) Reset() {
	*x = NodePretty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodePretty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePretty) ProtoMessage() {}

func (x *NodePretty) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePretty.ProtoReflect.Descriptor instead.
func (*NodePretty) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{2}
}

func (x *NodePretty) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodePretty) GetLabels() []*LabelPretty {
	if x != nil {
		return x.Labels
	}
	return nil
}

type LabelPretty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LabelPretty) Reset() {
	*x = LabelPretty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabelPretty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelPretty) ProtoMessage() {}

func (x *LabelPretty) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelPretty.ProtoReflect.Descriptor instead.
func (*LabelPretty) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{3}
}

func (x *LabelPretty) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelPretty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabelKey string `protobuf:"bytes,3,opt,name=labelKey,proto3" json:"labelKey,omitempty"`
	ShouldBe string `protobuf:"bytes,2,opt,name=shouldBe,proto3" json:"shouldBe,omitempty"`
	Value    string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{4}
}

func (x *Query) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *Query) GetShouldBe() string {
	if x != nil {
		return x.ShouldBe
	}
	return ""
}

func (x *Query) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_magnetar_proto protoreflect.FileDescriptor

var file_magnetar_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x31, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x65, 0x74, 0x74,
	0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x42, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x65, 0x74, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x72,
	0x65, 0x74, 0x74, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x35, 0x0a, 0x0b,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x74, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x75,
	0x6c, 0x64, 0x42, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x75,
	0x6c, 0x64, 0x42, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x3b, 0x0a, 0x08, 0x4d, 0x61,
	0x67, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x12, 0x2f, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_magnetar_proto_rawDescOnce sync.Once
	file_magnetar_proto_rawDescData = file_magnetar_proto_rawDesc
)

func file_magnetar_proto_rawDescGZIP() []byte {
	file_magnetar_proto_rawDescOnce.Do(func() {
		file_magnetar_proto_rawDescData = protoimpl.X.CompressGZIP(file_magnetar_proto_rawDescData)
	})
	return file_magnetar_proto_rawDescData
}

var file_magnetar_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_magnetar_proto_goTypes = []interface{}{
	(*QueryNodesReq)(nil),  // 0: QueryNodesReq
	(*QueryNodesResp)(nil), // 1: QueryNodesResp
	(*NodePretty)(nil),     // 2: NodePretty
	(*LabelPretty)(nil),    // 3: LabelPretty
	(*Query)(nil),          // 4: Query
}
var file_magnetar_proto_depIdxs = []int32{
	4, // 0: QueryNodesReq.queries:type_name -> Query
	2, // 1: QueryNodesResp.nodes:type_name -> NodePretty
	3, // 2: NodePretty.labels:type_name -> LabelPretty
	0, // 3: Magnetar.QueryNodes:input_type -> QueryNodesReq
	1, // 4: Magnetar.QueryNodes:output_type -> QueryNodesResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_magnetar_proto_init() }
func file_magnetar_proto_init() {
	if File_magnetar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_magnetar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodePretty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabelPretty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_magnetar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_magnetar_proto_goTypes,
		DependencyIndexes: file_magnetar_proto_depIdxs,
		MessageInfos:      file_magnetar_proto_msgTypes,
	}.Build()
	File_magnetar_proto = out.File
	file_magnetar_proto_rawDesc = nil
	file_magnetar_proto_goTypes = nil
	file_magnetar_proto_depIdxs = nil
}
