// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: magnetar.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MagnetarClient is the client API for Magnetar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MagnetarClient interface {
	QueryNodes(ctx context.Context, in *QueryNodesReq, opts ...grpc.CallOption) (*QueryNodesResp, error)
}

type magnetarClient struct {
	cc grpc.ClientConnInterface
}

func NewMagnetarClient(cc grpc.ClientConnInterface) MagnetarClient {
	return &magnetarClient{cc}
}

func (c *magnetarClient) QueryNodes(ctx context.Context, in *QueryNodesReq, opts ...grpc.CallOption) (*QueryNodesResp, error) {
	out := new(QueryNodesResp)
	err := c.cc.Invoke(ctx, "/Magnetar/QueryNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagnetarServer is the server API for Magnetar service.
// All implementations must embed UnimplementedMagnetarServer
// for forward compatibility
type MagnetarServer interface {
	QueryNodes(context.Context, *QueryNodesReq) (*QueryNodesResp, error)
	mustEmbedUnimplementedMagnetarServer()
}

// UnimplementedMagnetarServer must be embedded to have forward compatible implementations.
type UnimplementedMagnetarServer struct {
}

func (UnimplementedMagnetarServer) QueryNodes(context.Context, *QueryNodesReq) (*QueryNodesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNodes not implemented")
}
func (UnimplementedMagnetarServer) mustEmbedUnimplementedMagnetarServer() {}

// UnsafeMagnetarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MagnetarServer will
// result in compilation errors.
type UnsafeMagnetarServer interface {
	mustEmbedUnimplementedMagnetarServer()
}

func RegisterMagnetarServer(s grpc.ServiceRegistrar, srv MagnetarServer) {
	s.RegisterService(&Magnetar_ServiceDesc, srv)
}

func _Magnetar_QueryNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnetarServer).QueryNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Magnetar/QueryNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnetarServer).QueryNodes(ctx, req.(*QueryNodesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Magnetar_ServiceDesc is the grpc.ServiceDesc for Magnetar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Magnetar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Magnetar",
	HandlerType: (*MagnetarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryNodes",
			Handler:    _Magnetar_QueryNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magnetar.proto",
}
