// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: magnetar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryNodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *QueryNodesReq) Reset() {
	*x = QueryNodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesReq) ProtoMessage() {}

func (x *QueryNodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesReq.ProtoReflect.Descriptor instead.
func (*QueryNodesReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{0}
}

func (x *QueryNodesReq) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

type QueryNodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeStringified `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *QueryNodesResp) Reset() {
	*x = QueryNodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesResp) ProtoMessage() {}

func (x *QueryNodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesResp.ProtoReflect.Descriptor instead.
func (*QueryNodesResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{1}
}

func (x *QueryNodesResp) GetNodes() []*NodeStringified {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PutLabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Label  *Label `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *PutLabelReq) Reset() {
	*x = PutLabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLabelReq) ProtoMessage() {}

func (x *PutLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLabelReq.ProtoReflect.Descriptor instead.
func (*PutLabelReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{2}
}

func (x *PutLabelReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PutLabelReq) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

type PutLabelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *NodeStringified `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *PutLabelResp) Reset() {
	*x = PutLabelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutLabelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLabelResp) ProtoMessage() {}

func (x *PutLabelResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLabelResp.ProtoReflect.Descriptor instead.
func (*PutLabelResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{3}
}

func (x *PutLabelResp) GetNode() *NodeStringified {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegistrationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Labels []*Label `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *RegistrationReq) Reset() {
	*x = RegistrationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationReq) ProtoMessage() {}

func (x *RegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationReq.ProtoReflect.Descriptor instead.
func (*RegistrationReq) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationReq) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegistrationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
}

func (x *RegistrationResp) Reset() {
	*x = RegistrationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnetar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResp) ProtoMessage() {}

func (x *RegistrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_magnetar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResp.ProtoReflect.Descriptor instead.
func (*RegistrationResp) Descriptor() ([]byte, []int) {
	return file_magnetar_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationResp) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_magnetar_proto protoreflect.FileDescriptor

var file_magnetar_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x3e, 0x0a,
	0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2c, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x49, 0x0a,
	0x0b, 0x50, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x3a, 0x0a, 0x0c, 0x50, 0x75, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x2a, 0x0a,
	0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x32, 0x7e, 0x0a, 0x08, 0x4d, 0x61, 0x67,
	0x6e, 0x65, 0x74, 0x61, 0x72, 0x12, 0x3b, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x35, 0x0a, 0x08, 0x50, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_magnetar_proto_rawDescOnce sync.Once
	file_magnetar_proto_rawDescData = file_magnetar_proto_rawDesc
)

func file_magnetar_proto_rawDescGZIP() []byte {
	file_magnetar_proto_rawDescOnce.Do(func() {
		file_magnetar_proto_rawDescData = protoimpl.X.CompressGZIP(file_magnetar_proto_rawDescData)
	})
	return file_magnetar_proto_rawDescData
}

var file_magnetar_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_magnetar_proto_goTypes = []interface{}{
	(*QueryNodesReq)(nil),    // 0: proto.QueryNodesReq
	(*QueryNodesResp)(nil),   // 1: proto.QueryNodesResp
	(*PutLabelReq)(nil),      // 2: proto.PutLabelReq
	(*PutLabelResp)(nil),     // 3: proto.PutLabelResp
	(*RegistrationReq)(nil),  // 4: proto.RegistrationReq
	(*RegistrationResp)(nil), // 5: proto.RegistrationResp
	(*Query)(nil),            // 6: proto.Query
	(*NodeStringified)(nil),  // 7: proto.NodeStringified
	(*Label)(nil),            // 8: proto.Label
}
var file_magnetar_proto_depIdxs = []int32{
	6, // 0: proto.QueryNodesReq.queries:type_name -> proto.Query
	7, // 1: proto.QueryNodesResp.nodes:type_name -> proto.NodeStringified
	8, // 2: proto.PutLabelReq.label:type_name -> proto.Label
	7, // 3: proto.PutLabelResp.node:type_name -> proto.NodeStringified
	8, // 4: proto.RegistrationReq.labels:type_name -> proto.Label
	0, // 5: proto.Magnetar.QueryNodes:input_type -> proto.QueryNodesReq
	2, // 6: proto.Magnetar.PutLabel:input_type -> proto.PutLabelReq
	1, // 7: proto.Magnetar.QueryNodes:output_type -> proto.QueryNodesResp
	3, // 8: proto.Magnetar.PutLabel:output_type -> proto.PutLabelResp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_magnetar_proto_init() }
func file_magnetar_proto_init() {
	if File_magnetar_proto != nil {
		return
	}
	file_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_magnetar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutLabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutLabelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnetar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_magnetar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_magnetar_proto_goTypes,
		DependencyIndexes: file_magnetar_proto_depIdxs,
		MessageInfos:      file_magnetar_proto_msgTypes,
	}.Build()
	File_magnetar_proto = out.File
	file_magnetar_proto_rawDesc = nil
	file_magnetar_proto_goTypes = nil
	file_magnetar_proto_depIdxs = nil
}
